### PR TITLE
Add support for multiple 'Architecture' values

### PR DESCRIPTION
**Pull request by x1b6e6**
More info:
https://git.archlinux.org/pacman.git/commit/?id=3179db108a83104d9de6d1d607f55f8118e92160

### CODE REVIEW

**Comment by Morganamilo** [comment]
These functions need to go in the _five.go files are they are still part of pacman-git.

**Comment by Morganamilo** [comment]
Actually, I don't know how @jguer wants to handle it. These new functions break compatibility with the pacman-6 alpha. So we either add these function and break pacman-6 alpha support, or add a third build option for pacman-git.

**Comment by x1b6e6** [comment]
I can add `Arch()` and `SetArch()` to `handle_six.go` like this

```go
func (h *Handle) Arch() (string, error) {
    archs, err := h.GetArchitectures()
    if err != nil {
        return "", err
    }
    return archs.Slice()[0], nil
}

func (h *Handle) SetArch(str string) error {
    return SetArchitectures([]string{str})
}
```

`Arch()` looks scary but it add back compatibility (not full but something).

**Comment by Morganamilo** [comment]
That would make the go-alpm api stay the same but it will still break compatibility with old libalpm versions.

**Comment by Jguer** [comment]
I can't seem to find `pacman-6 alpha` "packaged" on the AUR, if that's the case I'm ok with breaking support for it, as all users should be following `pacman-git`

WDYT @Morganamilo ?

**Comment by x1b6e6** [comment]
I added support for 6x version before multi-arch support. `Makefile` looks ugly at now. If it's not needed then i'll gladly revert this commit.

**Comment by Morganamilo** [comment]
> I can't seem to find pacman-6 alpha "packaged" on the AUR,

It's packaged as a binary here: http://allanmcrae.com/2020/12/pacman-6-0-0alpha1/

Can't say how many people use it though.

**Comment by x1b6e6** [comment]
I have done runtime version checking support.

patch `alpm.go`:
```diff
diff --git a/alpm.go b/alpm.go
index d4d8bc4..5a77da6 100644
--- a/alpm.go
+++ b/alpm.go
@@ -6,7 +6,7 @@

 package alpm

-// #cgo LDFLAGS: -lalpm
+// #cgo LDFLAGS: -lalpm -ldl
 // #include <alpm.h>
 import "C"
```

patch `handle.go`:
```diff
diff --git a/handle.go b/handle.go
index cf92352..a126722 100644
--- a/handle.go
+++ b/handle.go
@@ -14,6 +14,8 @@ package alpm
 // #include <alpm.h>
 // #include <stdio.h> //C.free
 // #include <fnmatch.h> //C.FNM_NOMATCH
+// char* go_alpm_option_get_arch(alpm_handle_t*);
+// int go_alpm_option_set_arch(alpm_handle_t*,const char*);
 import "C"

 import (
@@ -427,13 +429,13 @@ func (h *Handle) AddAssumeInstalled(dep Depend) error {

 func (h *Handle) Arch() (string, error) {
        return h.optionGetStr(func(handle *C.alpm_handle_t) *C.char {
-               return C.alpm_option_get_arch(handle)
+               return C.go_alpm_option_get_arch(handle)
        })
 }

 func (h *Handle) SetArch(str string) error {
        return h.optionSetStr(str, func(handle *C.alpm_handle_t, cStr *C.char) C.int {
-               return C.alpm_option_set_arch(handle, cStr)
+               return C.go_alpm_option_set_arch(handle, cStr)
        })
 }

```

`handle.c`:
```c
#include <alpm.h>
#include <dlfcn.h>
#include <string.h>

char *go_alpm_option_get_arch(alpm_handle_t *handle) {
	void *libalpm = dlopen("alpm", RTLD_LAZY | RTLD_LOCAL);
	char *(*get_arch)(alpm_handle_t *) = dlsym(libalpm, "alpm_option_get_arch");

	if (get_arch != NULL) {
		return get_arch(handle);
	}
	
	alpm_list_t *(*get_architectures)(alpm_handle_t *) =
		dlsym(libalpm, "alpm_option_get_architectures");

	alpm_list_t *archs = get_architectures(handle);
	char *arch = strdup((const char *)archs->data);

	return arch;
}

int go_alpm_option_set_arch(alpm_handle_t *handle, const char *arch) {
	void *libalpm = dlopen("alpm", RTLD_LAZY | RTLD_LOCAL);
	int (*set_arch)(alpm_handle_t *, const char *) =
		dlsym(libalpm, "alpm_option_set_arch");

	if (set_arch != NULL) {
		return set_arch(handle, arch);
	}

	int (*set_architectures)(alpm_handle_t *, alpm_list_t *) =
		dlsym(libalpm, "alpm_option_set_architectures");

	alpm_list_t *archs;
	alpm_list_append(&archs, strdup(arch));
	int ret = set_architectures(handle, archs);

	alpm_list_free(archs);

	return ret;
}
```

This version will work after updat `pacman` without recompilation this library.
But `get_arch` just return first value from list. It's looks agly.

**Comment by Jguer** [comment]
@x1b6e6 I'd be in favor of dropping support for the alpha version of pacman. If you want to revert that last commit.

Support without recompilation is interesting, a bit slower probably but not where we'd lose most perf anyway. 

I'd be ok with the first version and then investigate using dynamic loading, would that be ok with you @x1b6e6 ?

**Comment by x1b6e6** [comment]
@Jguer I'm ok. I'll revert last commit. Runtime version at https://github.com/x1b6e6/go-alpm/tree/patch-2.

**Comment by Jguer** [comment]
@x1b6e6 run `make fmt` and it should be all good to merge :+1:

**Comment by x1b6e6** [comment]
@Jguer `make fmt` touches files that I did not touch. Send them?
<details>
<summary>diff</summary>

```diff
diff --git a/testdata/examples/updates/updates.go b/testdata/examples/updates/updates.go
index 786ec8c..58a5206 100644
--- a/testdata/examples/updates/updates.go
+++ b/testdata/examples/updates/updates.go
@@ -8,8 +8,8 @@ package main

 import (
        "fmt"
-       "log"
        paconf "github.com/Morganamilo/go-pacmanconf"
+       "log"
 )

 func human(size int64) string {
@@ -53,7 +53,6 @@ func main() {
        }
        defer h.Release()

-
        PacmanConfig, _, err := paconf.ParseFile("/etc/pacman.conf")
        if err != nil {
                fmt.Println(err)
@@ -72,12 +71,13 @@ func main() {
                }
                db.SetServers(repo.Servers)

-
                /*
                        Configure repository usage to match with
                        the alpm library provided formats
                */
-               if len(repo.Usage) == 0 { db.SetUsage(alpm.UsageAll) }
+               if len(repo.Usage) == 0 {
+                       db.SetUsage(alpm.UsageAll)
+               }
                for _, usage := range repo.Usage {
                        switch usage {
                        case "Sync":

```

</details>

**Pull request merged**
