### PR TITLE
Morten/alpm filelist contains

### PR DESCRIPTION
**Pull request by Foxboron**

### CODE REVIEW

**Comment by Jguer** [comment]
The first issue with travis was fixed but I'm unable to reproduce in my chroot what's causing the SIGSEV

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x55f312]
goroutine 9 [running]:
testing.tRunner.func1(0xc0000cad00)
	/usr/lib/go/src/testing/testing.go:830 +0x392
panic(0x598ae0, 0x725180)
	/usr/lib/go/src/runtime/panic.go:522 +0x1b5
_/build.(*Package).ContainsFile.func1.1(0x0, 0xc00002fed8)
	/build/package.go:186 +0x22
_/build.(*Package).ContainsFile.func1(0x0, 0x5cb449, 0x10, 0xa481d0)
	/build/package.go:186 +0x2f
_/build.(*Package).ContainsFile(0x0, 0x5cb449, 0x10, 0x0, 0xc000010370, 0x0, 0x0, 0x1d7542e7, 0x1d7542e7006bc130)
	/build/package.go:186 +0x43
_/build.TestPkgFiles(0xc0000cad00)
	/build/package_test.go:119 +0x159
testing.tRunner(0xc0000cad00, 0x5d4290)
	/usr/lib/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:916 +0x35a
exit status 2
```

**Comment by Foxboron** [comment]
And there we go. There was an `== nil` vs `!= nil` error and I have a slight hunch `linux` isn't on the docker image. Moved the file check to `glibc`

**Comment by Jguer** [comment]
Beautiful, everything seems in accordance, didn't think of that small detail of the image

**Comment by Morganamilo** [comment]
As mentioned on irc, `CSrings` need to be `Free`'d. Although it's not like we're perfect when it comes to leaking memory.

**Pull request merged**
