### PR TITLE
Dynamic load libalpm.so

### PR DESCRIPTION
**Pull request by x1b6e6**
Support `pacman` and `pacman-git` without rebuilding `yay`.

Warning: has a lot of C. Maybe I didn't notice something.

### CODE REVIEW

**Comment by Morganamilo** [comment]
What happens when pacman-git has another api or abi breaking change? and then another? And another? How many versions of alpm are going to be compatible? Also users will still need to rebuild for the newer alpms. So I don't see much of a use.

**Comment by x1b6e6** [comment]
@Morganamilo

> This would ease the migration between versions and after the majority of users has migrated to pacman 6, we'd remove the _five.go flag/files and return to complete static linking.

[As Jguer wrote](https://github.com/Jguer/yay/pull/1499#issuecomment-831717454)

**Comment by Morganamilo** [comment]
I'm not a fan of dlopen in general. Switching back and forth just so people don't have to rebuild yay seem's a bit silly to me.

**Comment by Jguer** [comment]
Unfortunately this is not how I really envisioned this feature. 

My objective would be to provide a soft migration to pacman 6 coming from pacman 5. So all this dl_open open would be kept on alpm_five files and alpm_six files would be kept as they are right now.

Once pacman 6 is released as stable and after a while we drop these alpm_five files (by then users will have already installed a new version of yay using that pacman 6 feature flag).

**Comment by x1b6e6** [comment]
> I'm not a fan of dlopen in general.

I'm not a fan too. But common user does not and should not know what 'rebuild' is. Maybe if they using `yay` then they know what they are doing, but usually it doesn't.

@Jguer, currently dlopen is only used if compiled without the `six` tag. When using the `six` tag, using normal binding.

Also api is universal with and without tag `six`.

**Comment by Morganamilo** [comment]
> But common user does not and should not know what 'rebuild' is

As an user of the AUR they should imo.

But I'm just shouting my opinions, It's up to Jguer.

**Comment by Jguer** [comment]
Seems we won't have time to test this. We're going manual this time

**Comment by x1b6e6** [comment]
Close?

**Comment by Jguer** [comment]
Thanks @x1b6e6 , sorry we didn't have the time to implement this

**Pull request closed without merging**
