### PR TITLE
Remove delta support

### PR DESCRIPTION
**Pull request by rumpelsepp**
Delta support has been removed from pacman 5.2.

### CODE REVIEW

**Comment by rumpelsepp** [comment]
Test is failing, since the test vm has not yet pacman 5.2.0

**Comment by rumpelsepp** [comment]
Should be ready. My local `yay` works now with pacman 5.2.

**Comment by Morganamilo** [comment]
Thanks, but hese changes are already in the pacman-next branch.

**Comment by rumpelsepp** [comment]
Ah. nice :smile:

**Pull request closed without merging**
