### PR TITLE
Update for Pacman 5.1

### PR DESCRIPTION
**Pull request by Morganamilo**
Fixes so this can be built against the new alpm release. Installing a couple of packages with Yay built against this seems to work fine.

The PKGBUILD should have a versioned dependency on pacman>=5.1

### CODE REVIEW

**Comment by Morganamilo** [comment]
Pacman 5.1 is in staging now. Preferably a new release of Yay will come along the second it hits core. I think this should be merged now and we can pull the update through dep when we're ready.

**Comment by Jguer** [comment]
Fair enough, actually had my hand over the merge today. It will just break people who don't want to use vendored, but I guess it won't be for long

**Comment by Jguer** [comment]
On testing now 
`yay: error while loading shared libraries: libalpm.so.10: cannot open shared object file: No such file or directory` of course

But yay with the 5.1 alpm patch seems to be working fine. Thinking now how we will deal with the update. Seems like a chicken and the egg problem

**Comment by Jguer** [comment]
It's in core actually now

**Comment by Morganamilo** [comment]
Oh boy if it's in core already then, update through dep and make a new release right away, make sure to have the versioned dep too.

**Comment by Jguer** [comment]
on it, write me the versioned string please while I update the tags

**Comment by Morganamilo** [comment]
depending on `pacman>=5.1` should be all you need.

**Comment by Jguer** [comment]
Yes, already added it `yay-bin` is out

**Comment by Jguer** [comment]
2 big ones are out. Tuning `yay-git` but most should be covered. Adding a manual upgrade warning to the release as well and should be done

**Comment by Jguer** [comment]
All done on my end, was expecting it to drop soon, not so soon though, caught me a bit off guard

**Comment by Morganamilo** [comment]
Yep, stuff like the kernel usually stays a week in testing, I assumed something as important as Packman would too. But then again seems as Pacman is developed on arch its kind of been tested all this time.

I had the change to update just now, Pacman and Yay both got updated in the same `Yay -Syu` and they both still work. Good job.

**Comment by Jguer** [comment]
Good thing I held off on sleep. Let's hope everyone will follow the same upgrade path :angel:. 
Either way I added a little explanation for people who botched their update and followed an online guide to install `yay` the first time

**Pull request merged**
